# THOR Agent - Minimal Configuration
wake_word:
  name: "THOR"
  sensitivity: 0.5

audio:
  sample_rate: 16000
  channels: 1

stt:
  engine: "whisper"
  whisper_model: "base"
  language: "de"

llm:
  providers:
    local:
      type: "lm-studio"
      endpoint: "http://localhost:1234/v1"
      model: "phi-4-mini-reasoning"
      temperature: 0.1
      max_tokens: 1000
    remote:
      type: "anthropic"
      model: "claude-3-sonnet-20241022"
      temperature: 0.3
      max_tokens: 1500
  routing:
    simple_patterns: ["kopiere", "verschiebe", "lösche", "erstelle", "zeige"]
    use_local_for_simple: true
  personas:
    assistant:
      name: "Personal Assistant THOR"
      prompt: "Du bist THOR, mein persönlicher KI-Assistent."

tts:
  engine: "elevenlabs"
  elevenlabs:
    voice_id: null
    model: "eleven_multilingual_v2"
  pyttsx3:
    rate: 150
    volume: 0.9

system:
  allowed_operations:
    - copy
    - move
    - list
    - create_folder
    - delete
    - search
  restricted_paths:
    - "/System"
    - "/Library"
  personal_spaces:
    downloads: "/Users/benjaminpoersch/Downloads"
    documents: "/Users/benjaminpoersch/Documents"
    marsap: "/Users/benjaminpoersch/MARSAP"

memory:
  storage_path: "data/memory"

mind:
  storage_path: "data/mind"

logging:
  level: "INFO"
  file: "logs/thor.log"
